function [gIs,gIv] = CalcGlobIndex(dim, pOrd, Mesh, ie, is)
NNODE = Mesh.NNODE;
NELE = Mesh.NELE;
NSPIG = Mesh.NSPIG;
switch dim
    case 1
        gIv = abs(Mesh.spig(ie,is));
        nIdx = Mesh.spig2(gIv,:);
        switch pOrd
            case 1
                gIs = nIdx;
            case 2
                gIs = [nIdx NNODE+abs(gIv)];
            case 3
                gIs = [nIdx NNODE+abs(gIv) NNODE+NSPIG+abs(gIv)];
            case 4
                gIs = [nIdx NNODE+abs(gIv) ...
                    NNODE+NSPIG+abs(gIv) NNODE+2*NSPIG+NELE+abs(gIv)];
        end
    case 2
        ele = Mesh.ele(ie,:);
        spig = abs(Mesh.spig(ie,:));
        switch pOrd
            case 1
                gIs = ele;
                gIv = abs(Mesh.spig(ie,:));
            case 2
                gIs = [ele NNODE+spig];
                gIv = [abs(Mesh.spig(ie,:)) Mesh.NSPIG+abs(Mesh.spig(ie,:)) ...
                    2*Mesh.NSPIG+ie 2*Mesh.NSPIG+Mesh.NELE+ie];
            case 3           
                gIs = [ele NNODE+spig ...
                    NNODE+NSPIG+spig NNODE+2*NSPIG+ie];
                gIv = [abs(Mesh.spig(ie,:)) Mesh.NSPIG+abs(Mesh.spig(ie,:)) ...
                    2*Mesh.NSPIG+ie 2*Mesh.NSPIG+Mesh.NELE+ie ...
                    2*Mesh.NSPIG+2*Mesh.NELE+abs(Mesh.spig(ie,:))...
                    3*Mesh.NSPIG+2*Mesh.NELE+ie ...
                    3*Mesh.NSPIG+3*Mesh.NELE+ie ...
                    3*Mesh.NSPIG+4*Mesh.NELE+ie ...
                    3*Mesh.NSPIG+5*Mesh.NELE+ie];
             case 4
                gIs = [ele NNODE+spig ...
                    NNODE+NSPIG+spig NNODE+2*NSPIG+ie ...
                    NNODE+2*NSPIG+NELE+spig NNODE+3*NSPIG+NELE+ie ...
                    NNODE+3*NSPIG+2*NELE+ie];
                gIv = [abs(Mesh.spig(ie,:)) Mesh.NSPIG+abs(Mesh.spig(ie,:)) ...
                    2*Mesh.NSPIG+ie 2*Mesh.NSPIG+Mesh.NELE+ie ...
                    2*Mesh.NSPIG+2*Mesh.NELE+abs(Mesh.spig(ie,:))...
                    3*Mesh.NSPIG+2*Mesh.NELE+ie ...
                    3*Mesh.NSPIG+3*Mesh.NELE+ie ...
                    3*Mesh.NSPIG+4*Mesh.NELE+ie ...
                    3*Mesh.NSPIG+5*Mesh.NELE+ie]; % and something more
        end
end
